[window]
padding = {x = 10, y = 10}
opacity = 0.8
decorations = "None"
decorations_theme_variant = "Dark"

[cursor]
vi_mode_style = {shape = "Block", blinking = "On"}
blink_interval = 300

[font.normal]
family = "JetbrainsMono Nerd Font"

[general]
import = ["~/.config/alacritty/catppuccin-latte.toml"]

[env]
TERM = "xterm-256color"


















































































