#:schema https://yazi-rs.github.io/schemas/theme.json

[flavor]
dark  = "catppuccin-mocha"
light = "catppuccin-mocha"

[app]
overall = { bg = "#1e1e2e" }

[mgr]
symlink_target = { fg = "#cba6f7", italic = true }

[indicator]
parent  = { fg = "#6c7086" }
current = { fg = "#1e1e2e", bg = "#89b4fa", bold = true }
preview = { fg = "#1e1e2e", bg = "#94e2d5" }
padding = { open = "▐", close = "▌" }

[confirm]
border  = { fg = "#89b4fa" }
title   = { fg = "#89b4fa", bold = true }
body    = { fg = "#cdd6f4" }
list    = { fg = "#cdd6f4" }
btn_yes = { fg = "#1e1e2e", bg = "#a6e3a1", bold = true }
btn_no  = { fg = "#1e1e2e", bg = "#f38ba8", bold = true }

[help]
border  = { fg = "#89b4fa" }
chord   = { fg = "#94e2d5", bold = true }
action  = { fg = "#cdd6f4" }
hovered = { fg = "#1e1e2e", bg = "#89b4fa", bold = true }

[filetype]
rules = [
	{ url = "*",  is = "orphan", fg = "#f38ba8", bold = true },
	{ url = "*",  is = "link",   fg = "#cba6f7", italic = true },
	{ url = "*",  is = "exec",   fg = "#a6e3a1" },
	{ url = "*",  is = "dummy",  fg = "#1e1e2e", bg = "#f38ba8" },
	{ url = "*/", is = "dummy",  fg = "#1e1e2e", bg = "#f38ba8" },
	{ mime = "**/image/*", fg = "#94e2d5" },
	{ mime = "**/{audio,video}/*", fg = "#f9e2af" },
	{ mime = "**/application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },
	{ mime = "**/application/{pdf,doc,rtf}", fg = "#a6e3a1" },
	{ mime = "vfs/{absent,stale}", fg = "#9399b2" },
	{ url = "*", fg = "#cdd6f4" },
	{ url = "*/", fg = "#89b4fa", bold = true },
]

[icon]
prepend_files = [
	{ name = "bspwmrc", text = "", fg = "#6c7086" },
	{ name = "gemfile", text = "", fg = "#f38ba8" },
	{ name = "rakefile", text = "", fg = "#f38ba8" },
	{ name = "vagrantfile", text = "", fg = "#b4befe" },
]
prepend_conds = [
	{ if = "orphan", text = "", fg = "#f38ba8" },
	{ if = "link", text = "", fg = "#cba6f7" },
	{ if = "exec", text = "", fg = "#a6e3a1" },
]
