[mgr]
show_hidden = false
show_symlink = true

[opener]
archive = [{ run = 'ya pub extract --list %s', desc = "Extract here" }]
gimp = [{ run = 'gimp %s', desc = "Open with GIMP", orphan = true }]
inkscape = [{ run = 'inkscape %s', desc = "Open with Inkscape", orphan = true }]
kdenlive = [{ run = 'flatpak run org.kde.kdenlive %s', desc = "Open with Kdenlive", orphan = true }]
libreoffice = [{ run = 'libreoffice %s', desc = "Open with LibreOffice", orphan = true }]
loupe = [{ run = 'flatpak run org.gnome.Loupe %s', desc = "Open image with Loupe", orphan = true }]
editor = [{ run = '$EDITOR %s', desc = "Edit with $EDITOR", block = true }]
papers = [{ run = 'flatpak run org.gnome.Papers %s', desc = "Open PDF with GNOME Papers", orphan = true }]
prusa = [{ run = 'flatpak run com.prusa3d.PrusaSlicer %s', desc = "Open gcode with Prusa Slicer", orphan = true }]
vlc = [{ run = 'flatpak run org.videolan.VLC %s', desc = "Play with VLC", orphan = true }]

# Map file types to openers
[open]
prepend_rules = [
  { mime = "application/pdf", use = "papers" },
  { url  = "*.gcode", use = "prusa" },
  { mime = "image/svg+xml", use = "inkscape" },
  { url  = "*.xcf", use = "gimp" },
  { mime = "image/*", use = "loupe" },
  { mime = "video/*", use = "vlc" },
  { mime = "audio/*", use = "vlc" },
  { url  = "*.kdenlive", use = "kdenlive" },
  { url  = "*.3mf", use = "prusa" },
  { mime = "application/vnd.oasis.opendocument.text", use = "libreoffice" },
  { mime = "application/vnd.oasis.opendocument.text-template", use = "libreoffice" },
  { mime = "application/msword", use = "libreoffice" },
  { mime = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", use = "libreoffice" },
  { mime = "application/vnd.openxmlformats-officedocument.wordprocessingml.template", use = "libreoffice" },
  { mime = "application/vnd.oasis.opendocument.spreadsheet", use = "libreoffice" },
  { mime = "application/vnd.oasis.opendocument.spreadsheet-template", use = "libreoffice" },
  { mime = "application/vnd.ms-excel", use = "libreoffice" },
  { mime = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", use = "libreoffice" },
  { mime = "application/vnd.openxmlformats-officedocument.spreadsheetml.template", use = "libreoffice" },
  { mime = "application/vnd.oasis.opendocument.presentation", use = "libreoffice" },
  { mime = "application/vnd.oasis.opendocument.presentation-template", use = "libreoffice" },
  { mime = "application/vnd.ms-powerpoint", use = "libreoffice" },
  { mime = "application/vnd.openxmlformats-officedocument.presentationml.presentation", use = "libreoffice" },
  { mime = "application/vnd.openxmlformats-officedocument.presentationml.template", use = "libreoffice" },
  { mime = "application/vnd.oasis.opendocument.graphics", use = "libreoffice" },
  { mime = "application/vnd.oasis.opendocument.graphics-template", use = "libreoffice" },
  { mime = "application/zip", use = "archive" },
  { mime = "application/x-tar", use = "archive" },
  { mime = "application/x-bzip2", use = "archive" },
  { mime = "application/x-xz", use = "archive" },
  { mime = "application/x-7z-compressed", use = "archive" },
  { mime = "application/x-rar", use = "archive" },
  { mime = "text/*", use = "editor" }
]
